// Package yamltags provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package yamltags

// CookieParamsParams defines parameters for CookieParams.
type CookieParamsParams struct {
	// AuthId Cookie parameter
	AuthId *string `form:"authId,omitempty" json:"authId,omitempty" yaml:"authId,omitempty"`

	// ServerId Another cookie parameter
	ServerId *string `form:"serverId,omitempty" json:"serverId,omitempty" yaml:"serverId,omitempty"`
}
