// Package issue1469 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package issue1469

import (
	"github.com/gofiber/fiber/v3"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /test)
	Test(c fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
	ErrFn   func(c fiber.Ctx, err error) error
}

type MiddlewareFunc fiber.Handler

// Test operation middleware
func (siw *ServerInterfaceWrapper) Test(c fiber.Ctx) error {

	return siw.Handler.Test(c)
}

type OpName = string

const (
	OpNameValueTest OpName = "Test"
)

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface, hs map[OpName][]fiber.Handler, errFn func(c fiber.Ctx, err error) error) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{}, hs, errFn)
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions, hs map[OpName][]fiber.Handler, errFn func(c fiber.Ctx, err error) error) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
		ErrFn:   errFn,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	hsTest := append(hs["Test"], wrapper.Test)
	router.Get(options.BaseURL+"/test", hsTest[0], hsTest[1:]...)

}
